### ISSUE TITLE
Hard requirement on six == 1.10.0

### ISSUE THREAD

**Issue by mssalvatore** [TheClimateCorporation/python-dpkg#13]
I'm interested in using python-dpkg in my project. My project is currently dependent upon other packages which require six >= 1.14.0. This causes a version conflict as python-dpkg has a hard dependency on 1.10.0.

Does python-dpkg actually require exactly six 1.10.0, or would a later version be ok?

**Comment by memory** [comment]
I suspect that a later version would be fine; let me push an update to pypi that has a less specific dependency.  Will probably get to it later tonight or tomorrow.

**Comment by memory** [comment]
https://github.com/memory/python-dpkg/pull/2

**Comment by mssalvatore** [comment]
@memory That should solve my issue :)

As a quick aside, it looks like maybe creating issues in memory/python-dpkg is disabled.

**Comment by memory** [comment]
Oops, enabled issues there :)

**Comment by memory** [comment]
1.4.4 is now published to both pypi and github; enjoy!

**Comment by mssalvatore** [comment]
Thank you!
